language: node_js

sudo: false

env: 
 - NODE_JS_VERSION='0.10'
 - NODE_JS_VERSION='0.11'


install: 
 - nvm use $NODE_JS_VERSION
 - npm install
script:
 - npm start
 - true

node_js:
 - "0.10"
 - "0.11"
